CREATE TABLE MARKET_DATA (
    SYMBOL        VARCHAR(32) NOT NULL,
    TRADE_DATE    DATE        NOT NULL,
    CLOSE_PRICE   DECIMAL(18,6),
    VOLUME        BIGINT,
    PRIMARY KEY (SYMBOL, TRADE_DATE)
);
