CREATE VIEW QUANTUM_FEATURES AS
SELECT
    SYMBOL,
    TRADE_DATE,

    (CLOSE_PRICE - LAG(CLOSE_PRICE)
        OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE))
        / LAG(CLOSE_PRICE)
        OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE)
        AS RETURN,

    AVG(
        (CLOSE_PRICE - LAG(CLOSE_PRICE)
            OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE))
        / LAG(CLOSE_PRICE)
            OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE)
    ) OVER (
        PARTITION BY SYMBOL
        ORDER BY TRADE_DATE
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW
    ) AS TREND_STRENGTH,

    STDDEV(
        (CLOSE_PRICE - LAG(CLOSE_PRICE)
            OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE))
        / LAG(CLOSE_PRICE)
            OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE)
    ) OVER (
        PARTITION BY SYMBOL
        ORDER BY TRADE_DATE
        ROWS BETWEEN 10 PRECEDING AND CURRENT ROW
    ) AS VOLATILITY

FROM MARKET_DATA;
